# Setup
title:               jvpichowski
tagline:             'blog'
description:         'A computer sciences student on his way through a fascinating world.'
url:                 https://jvpichowski.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

github:
  repo:              https://github.com/jvpichowski         

# About/contact
author:
  name:              Jan von Pichowski
  url:               https://github.com/jvpichowski
#  email:             mail@mail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
# version:             1.1.0
# google_analytics_id: #UA-XXXX-Y
